/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.example.sleepy;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int about=0x7f08000c;
        public static final int about_content=0x7f080000;
        public static final int add=0x7f080009;
        public static final int add_button=0x7f080002;
        public static final int clock_text=0x7f080008;
        public static final int feed_url=0x7f080001;
        public static final int feeds=0x7f08000b;
        public static final int rowid=0x7f080003;
        public static final int rowidcolon=0x7f080004;
        public static final int settings=0x7f08000a;
        public static final int time=0x7f080005;
        public static final int timecolon=0x7f080006;
        public static final int title=0x7f080007;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int add_feed=0x7f030001;
        public static final int feed=0x7f030002;
        public static final int feeds=0x7f030003;
        public static final int main=0x7f030004;
    }
    public static final class menu {
        public static final int feeds_menu=0x7f070000;
        public static final int menu=0x7f070001;
    }
    public static final class string {
        public static final int about_label=0x7f060002;
        public static final int about_shortcut=0x7f060004;
        public static final int about_text=0x7f060005;
        public static final int about_title=0x7f060003;
        public static final int add_button=0x7f060010;
        public static final int add_shortcut=0x7f060011;
        public static final int add_title=0x7f06000d;
        public static final int app_name=0x7f060000;
        public static final int empty=0x7f060012;
        public static final int feed_text=0x7f06000f;
        public static final int feed_title=0x7f06000e;
        public static final int hints_summary=0x7f06000c;
        public static final int hints_title=0x7f06000b;
        public static final int main_title=0x7f060001;
        public static final int music_summary=0x7f06000a;
        public static final int music_title=0x7f060009;
        public static final int settings_label=0x7f060006;
        public static final int settings_shortcut=0x7f060008;
        public static final int settings_title=0x7f060007;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
